repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format code

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Lint code

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck
        name: Check CI Scripts
        additional_dependencies: []  # Workaround for pre-commit 2.10+
        exclude: '^(?!(ci-scripts/))'  # Negative lookahead, so will exclude everything except listed.
